<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Jadwal extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Jadwal_model');
        $this->load->library('pdf');
    }

    /*
     * Listing of jadwal
     */
    function index()
    {
        if ($this->session->userdata("level") == NULL) {
            $this->load->view('login/login');
        } else {
            $data['jadwal'] = $this->Jadwal_model->get_all_jadwal();

            $data['_view'] = 'jadwal/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    function cetak()
    {
        $pdf = new FPDF('P', 'mm', 'A4');
        // membuat halaman baru
        $pdf->AddPage();
        // setting jenis font yang akan digunakan
        $pdf->SetFont('Arial', 'B', 16);
        // mencetak string 
        $pdf->SetFont('Arial', 'B', 14);
        $pdf->Image('resources/img/poltek.png', 10, 6, 28);
        $pdf->Cell(190, 7, 'UPT SISTEM INFORMASI', 0, 1, 'C');
        $pdf->SetFont('Arial', 'B', 18);
        $pdf->Cell(190, 7, 'POLITEKNIK HARAPAN BERSAMA TEGAL', 0, 1, 'C');
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(190, 7, 'LAPORAN JADWAL', 0, 1, 'C');
        $pdf->SetFont('Arial', '', 9);
        //$pdf->Cell(190,6,'Periode '. date('d-m-Y', strtotime($tgl_awal)).' s/d '.date('d-m-Y', strtotime($tgl_ahir)),0,1,'C');

        // Memberikan space kebawah agar tidak terlalu rapat
        $pdf->Ln();
        $barang = $this->db->select('*');
        $barang = $this->db->from('lembur a');
        $barang = $this->db->join('asisten b', 'b.id_asisten=a.id_asisten', 'left');
        $barang = $this->db->join('hari c', 'c.id_hari=a.hari', 'left');
        $barang = $this->db->order_by('a.id', 'asc');
        $barang = $this->db->get()->result();

        $pdf->Ln();
        $pdf->Cell(10, 7, '', 0, 1);
        $pdf->SetFont('Arial', 'B', 9);
        $pdf->Cell(10, 8, 'NO.', 1, 0, 'C');
        $pdf->Cell(30, 8, 'NAMA BARANG', 1, 0);
        $pdf->Cell(25, 8, 'LOKASI', 1, 0);
        $pdf->Cell(25, 8, 'KETERANGAN BARANG', 1, 0);
        $pdf->Cell(25, 8, 'STATUS', 1, 0, 'C');
        $pdf->Cell(40, 8, 'TGL. MASUK', 1, 1, 'C');
        $pdf->SetFont('Arial', '', 9);

        $X = 0;
        foreach ($barang as $row) {
            $X += 1;
            $pdf->Cell(10, 6, $X, 1, 0, 'C');
            $pdf->Cell(30, 6, $row->nm_hari, 1, 0);
            $pdf->Cell(25, 6, date("d-m-Y", strtotime($row->tanggal)), 1, 0);
            $pdf->Cell(25, 6, $row->jam_mulai, 1, 1);
            $pdf->Cell(25, 6, $row->jam_pulang, 1, 1);
            $pdf->Cell(40, 6, $row->nm_asisten, 1, 1);
        }
        $pdf->Output();
    }
    /*
     * Adding a new jadwal
     */

    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'id_asisten' => $this->input->post('id_asisten'),
                'jam' => $this->input->post('jam'),
                'hari' => $this->input->post('hari'),
            );

            $jadwal_id = $this->Jadwal_model->add_jadwal($params);
            redirect('jadwal/index');
        } else {
            $data['asisten'] = $this->Jadwal_model->get_all_asisten();
            $data['jam'] = $this->Jadwal_model->get_all_jam();
            $data['hari'] = $this->Jadwal_model->get_all_hari();
            $data['_view'] = 'jadwal/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a jadwal
     */
    function edit($id_jadwal)
    {
        // check if the jadwal exists before trying to edit it
        $data['jadwal'] = $this->Jadwal_model->get_jadwal($id_jadwal);

        if (isset($data['jadwal']['id_jadwal'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'id_asisten' => $this->input->post('id_asisten'),
                    'jam' => $this->input->post('jam'),
                    'hari' => $this->input->post('hari'),
                );

                $this->Jadwal_model->update_jadwal($id_jadwal, $params);
                redirect('jadwal/index');
            } else {
                $data['asisten'] = $this->Jadwal_model->get_all_asisten();
                $data['jam'] = $this->Jadwal_model->get_all_jam();
                $data['hari'] = $this->Jadwal_model->get_all_hari();
                $data['_view'] = 'jadwal/edit';
                if ($this->session->userdata("level") == 'admin') {
                    $this->load->view('layouts/main', $data);
                } else {
                    $this->load->view('layouts/main_user', $data);
                }
            }
        } else
            show_error('The jadwal you are trying to edit does not exist.');
    }

    /*
     * Deleting jadwal
     */
    function remove($id_jadwal)
    {
        $jadwal = $this->Jadwal_model->get_jadwal($id_jadwal);

        // check if the jadwal exists before trying to delete it
        if (isset($jadwal['id_jadwal'])) {
            $this->Jadwal_model->delete_jadwal($id_jadwal);
            redirect('jadwal/index');
        } else
            show_error('The jadwal you are trying to delete does not exist.');
    }

    function lembur()
    {
        if ($this->session->userdata("level") == NULL) {
            $this->load->view('login/login');
        } else {
            $data['jadwal'] = $this->Jadwal_model->get_all_lembur();

            $data['_view'] = 'jadwal/lembur';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }
    function addlembur()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'hari' => $this->input->post('hari'),
                'tanggal' => $this->input->post('tanggal'),
                'jam_mulai' => $this->input->post('jam_mulai'),
                'jam_pulang' => $this->input->post('jam_pulang'),
                'id_asisten' => $this->input->post('id_asisten'),
                'kegiatan' => $this->input->post('kegiatan'),
            );

            $jadwal_id = $this->Jadwal_model->add_lembur($params);
            redirect('jadwal/lembur');
        } else {
            $data['asisten'] = $this->Jadwal_model->get_all_asisten();
            $data['jam'] = $this->Jadwal_model->get_all_jam();
            $data['hari'] = $this->Jadwal_model->get_all_hari();
            $data['_view'] = 'jadwal/addlembur';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }
    function editlembur($id)
    {
        // check if the jadwal exists before trying to edit it
        $data['jadwal'] = $this->Jadwal_model->get_lembur($id);

        if (isset($data['jadwal']['id'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'hari' => $this->input->post('hari'),
                    'tanggal' => $this->input->post('tanggal'),
                    'jam_mulai' => $this->input->post('jam_mulai'),
                    'jam_pulang' => $this->input->post('jam_pulang'),
                    'id_asisten' => $this->input->post('id_asisten'),
                    'kegiatan' => $this->input->post('kegiatan'),
                );

                $this->Jadwal_model->update_lembur($id, $params);
                redirect('jadwal/lembur');
            } else {
                $data['asisten'] = $this->Jadwal_model->get_all_asisten();
                $data['jam'] = $this->Jadwal_model->get_all_jam();
                $data['hari'] = $this->Jadwal_model->get_all_hari();
                $data['_view'] = 'jadwal/editlembur';
                if ($this->session->userdata("level") == 'admin') {
                    $this->load->view('layouts/main', $data);
                } else {
                    $this->load->view('layouts/main_user', $data);
                }
            }
        } else
            show_error('The jadwal you are trying to edit does not exist.');
    }
    function removelembur($id)
    {
        $jadwal = $this->Jadwal_model->get_lembur($id);

        // check if the jadwal exists before trying to delete it
        if (isset($jadwal['id'])) {
            $this->Jadwal_model->delete_lembur($id);
            redirect('jadwal/lembur');
        } else
            show_error('The jadwal you are trying to delete does not exist.');
    }

    function cetaklembur()
    {
        $tgl_awal = $this->input->post('tgl_awal');
        $tgl_ahir = $this->input->post('tgl_ahir');
        if ($tgl_awal != 0) {
            $pdf = new FPDF('P', 'mm', 'A4');
            // membuat halaman baru
            $pdf->AddPage();
            // setting jenis font yang akan digunakan
            $pdf->SetFont('Arial', 'B', 16);
            // mencetak string 
            $pdf->SetFont('Arial', 'B', 12);
            $pdf->Image('resources/img/poltek.png', 10, 6, 28);
            $pdf->Cell(190, 7, 'UPT SISTEM INFORMASI', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 14);
            $pdf->Cell(190, 7, 'POLITEKNIK HARAPAN BERSAMA TEGAL', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 11);
            $pdf->Cell(190, 7, 'ABSENSI LEMBUR KARYAWAN', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 9);
            $pdf->Cell(190, 6, 'Periode ' . date('d-m-Y', strtotime($tgl_awal)) . ' s/d ' . date('d-m-Y', strtotime($tgl_ahir)), 0, 1, 'C');

            $pdf->Cell(10, 7, '', 0, 1);
            $pdf->SetFont('Arial', 'B', 9);
            $pdf->Cell(10, 8, 'NO.', 1, 0, 'C');
            $pdf->Cell(20, 8, 'HARI', 1, 0, 'C');
            $pdf->Cell(25, 8, 'TANGGAL', 1, 0, 'C');
            $pdf->Cell(25, 8, 'JAM MASUK', 1, 0, 'C');
            $pdf->Cell(25, 8, 'JAM PULANG', 1, 0, 'C');
            $pdf->Cell(50, 8, 'NAMA', 1, 0, 'C');
            $pdf->Cell(40, 8, 'PARAF', 1, 1, 'C');
            $pdf->SetFont('Arial', '', 9);


            $barang = $this->db->select('*');
            $barang = $this->db->from('lembur a');
            $barang = $this->db->join('asisten b', 'b.id_asisten=a.id_asisten', 'left');
            $barang = $this->db->join('hari c', 'c.id_hari=a.hari', 'left');
            $barang = $this->db->where('a.tanggal BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
            $barang = $this->db->order_by('a.id', 'asc');
            $barang = $this->db->get()->result();

            $X = 0;
            foreach ($barang as $row) {
                $X += 1;
                $pdf->Cell(10, 6, $X, 1, 0, 'C');
                $pdf->Cell(20, 6, $row->nm_hari, 1, 0, 'C');
                $pdf->Cell(25, 6, date("d-m-Y", strtotime($row->tanggal)), 1, 0, 'C');
                $pdf->Cell(25, 6, $row->jam_mulai, 1, 0, 'C');
                $pdf->Cell(25, 6, $row->jam_pulang, 1, 0, 'C');
                $pdf->Cell(50, 6, $row->nm_asisten, 1, 0);
                $pdf->Cell(20, 6, $row->paraf, 1, 0);
                $pdf->Cell(20, 6, $row->paraf, 1, 1);
            }
            $pdf->Ln();
            // setting jenis font yang akan digunakan
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(190, 7, 'Tegal, ' . tanggal('d F Y'), 0, 1, 'R');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(190, 7, 'Mengetahui,', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 6, 'WADIR I', 0, 0, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 7, 'Ka. UPT. Sistem Informasi', 0, 1, 'C');
            $pdf->Cell(95, 7, 'Politeknik Harapan Bersama Tegal', 0, 0, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 6, 'Politeknik Harapan Bersama Tegal', 0, 1, 'C');
            $pdf->Ln();
            $pdf->Ln();
            $pdf->Ln();
            $pdf->SetFont('Arial', '' . 'U', 11);
            $pdf->Cell(95, 6, 'Arfan Haqiqi S., M.Kom', 0, 0, 'C');
            $pdf->SetFont('Arial', '' . 'U', 11);
            $pdf->Cell(95, 7, 'Miftakhul Huda, M.Kom', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 7, 'NIPY. 02.009.054', 0, 0, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 6, 'NIPY. 04.007.033', 0, 1, 'C');

            $pdf->Output();
        } else {
            $data['_view'] = 'jadwal/cetaklembur';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }
    function kegiatan()
    {
        $tgl_awal = $this->input->post('tgl_awal');
        $tgl_ahir = $this->input->post('tgl_ahir');
        if ($tgl_awal != 0) {
            $pdf = new FPDF('P', 'mm', 'A4');
            // membuat halaman baru
            $pdf->AddPage();
            // setting jenis font yang akan digunakan
            $pdf->SetFont('Arial', 'B', 16);
            // mencetak string 
            $pdf->SetFont('Arial', 'B', 12);
            $pdf->Image('resources/img/poltek.png', 10, 6, 28);
            $pdf->Cell(190, 7, 'UPT SISTEM INFORMASI', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 14);
            $pdf->Cell(190, 7, 'POLITEKNIK HARAPAN BERSAMA TEGAL', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 11);
            $pdf->Cell(190, 7, 'RINCIAN KEGIATAN LEMBUR', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 9);
            $pdf->Cell(190, 6, 'Periode ' . date('d-m-Y', strtotime($tgl_awal)) . ' s/d ' . date('d-m-Y', strtotime($tgl_ahir)), 0, 1, 'C');

            $pdf->Cell(10, 7, '', 0, 1);
            $pdf->SetFont('Arial', 'B', 9);
            $pdf->Cell(10, 8, 'NO.', 1, 0, 'C');
            $pdf->Cell(40, 8, 'HARI / TANGGAL', 1, 0, 'C');
            $pdf->Cell(25, 8, 'WAKTU', 1, 0, 'C');
            $pdf->Cell(110, 8, 'RINCIAN KEGIATAN', 1, 1, 'C');
            $pdf->SetFont('Arial', '', 9);


            $barang = $this->db->select('*');
            $barang = $this->db->from('lembur a');
            $barang = $this->db->join('asisten b', 'b.id_asisten=a.id_asisten', 'left');
            $barang = $this->db->join('hari c', 'c.id_hari=a.hari', 'left');
            $barang = $this->db->where('a.tanggal BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
            $barang = $this->db->order_by('a.id', 'asc');
            $barang = $this->db->get()->result();

            $X = 0;
            foreach ($barang as $row) {
                $X += 1;
                $pdf->Cell(10, 6, $X, 1, 0, 'C');
                $pdf->Cell(40, 6, $row->nm_hari . ', ' . date("d-m-Y", strtotime($row->tanggal)), 1, 0, 'C');
                $pdf->Cell(25, 6, $row->jam_mulai . ' - ' . $row->jam_pulang, 1, 0, 'C');
                $pdf->Cell(110, 6, $row->kegiatan, 1, 1);
            }
            $pdf->Ln();
            // setting jenis font yang akan digunakan
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(190, 7, 'Tegal, ' . tanggal('d F Y'), 0, 1, 'R');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 6, '', 0, 0, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 7, 'Mengetahui,', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 6, '', 0, 0, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 7, 'Ka. UPT. Sistem Informasi', 0, 1, 'C');
            $pdf->Cell(95, 7, '', 0, 0, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 6, 'Politeknik Harapan Bersama Tegal', 0, 1, 'C');
            $pdf->Ln();
            $pdf->Ln();
            $pdf->SetFont('Arial', '' . 'U', 11);
            $pdf->Cell(95, 6, '', 0, 0, 'C');
            $pdf->SetFont('Arial', '' . 'U', 11);
            $pdf->Cell(95, 7, 'Miftakhul Huda, M.Kom', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 7, '', 0, 0, 'C');
            $pdf->SetFont('Arial', '', 11);
            $pdf->Cell(95, 6, 'NIPY. 04.007.033', 0, 1, 'C');

            $pdf->Output();
        } else {
            $data['_view'] = 'jadwal/kegiatan';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }
    function rekap()
    { {
            $tgl_awal = $this->input->post('tgl_awal');
            $tgl_ahir = $this->input->post('tgl_ahir');
            if ($tgl_awal != 0) {
                $pdf = new FPDF('P', 'mm', 'A4');
                // membuat halaman baru
                $pdf->AddPage();
                // setting jenis font yang akan digunakan
                $pdf->SetFont('Arial', 'B', 16);
                // mencetak string 
                $pdf->SetFont('Arial', 'B', 14);
                $pdf->Cell(190, 7, 'REKAP HONOR LEMBUR KARYAWAN UPT. SISTEM INFORMASI', 0, 1, 'C');
                $pdf->SetFont('Arial', '', 9);
                $pdf->Cell(190, 6, 'Periode ' . date('d-m-Y', strtotime($tgl_awal)) . ' s/d ' . date('d-m-Y', strtotime($tgl_ahir)), 0, 1, 'C');

                $pdf->Cell(10, 7, '', 0, 1);
                $pdf->SetFont('Arial', 'B', 9);
                $pdf->Cell(10, 8, 'NO.', 1, 0, 'C');
                $pdf->Cell(60, 8, 'NAMA', 1, 0, 'C');
                $pdf->Cell(50, 8, 'HARI / TANGGAL', 1, 0, 'C');
                $pdf->Cell(35, 8, 'WAKTU', 1, 0, 'C');
                $pdf->Cell(30, 8, 'JUMLAH JAM', 1, 1, 'C');
                $pdf->SetFont('Arial', '', 9);

                //dodi
                $pdf->SetFont('Arial', '', 9);
                $dodi = $this->db->select('*');
                $dodi = $this->db->from('lembur a');
                $dodi = $this->db->join('asisten b', 'b.id_asisten=a.id_asisten', 'left');
                $dodi = $this->db->join('hari c', 'c.id_hari=a.hari', 'left');
                $dodi = $this->db->like('a.id_asisten', '102920');
                $dodi = $this->db->where('a.tanggal BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
                $dodi = $this->db->order_by('a.id', 'asc');
                $dodi = $this->db->get()->result();

                $X = 0;
                $tot1 = 0;

                foreach ($dodi as $row) {
                    $X += 1;
                    $t = $row->jam_pulang - $row->jam_mulai; //pengurangan jam pulang - jam masuk. 
                    $h = round($t * 2) / 2; //konversi pengurangan jam agar pas
                    $pdf->Cell(10, 6, $X, 1, 0, 'C');
                    $pdf->Cell(60, 6, $row->nm_asisten, 1, 0, 'C');
                    $pdf->Cell(50, 6, $row->nm_hari . ', ' . date("d-m-Y", strtotime($row->tanggal)), 1, 0, 'C');
                    $pdf->Cell(35, 6, $row->jam_mulai . ' - ' . $row->jam_pulang, 1, 0, 'C');
                    $pdf->Cell(30, 6, $h, 1, 1, 'C');
                    $tot1 += $h;
                }
                $total1 = $tot1 * 8000;
                $pdf->SetFont('Arial', 'B', 9);
                $pdf->Cell(155, 6, 'Total Jam', 1, 0, 'R');
                $pdf->Cell(30, 6, $tot1, 1, 1, 'C');
                $pdf->Cell(155, 6, 'Total Jam x 8000', 1, 0, 'R');
                $pdf->Cell(30, 6, 'Rp.  ' . $total1, 1, 1, 'C');
                //End Dodi

                //fikri
                $pdf->SetFont('Arial', '', 9);
                $fikri = $this->db->select('*');
                $fikri = $this->db->from('lembur a');
                $fikri = $this->db->join('asisten b', 'b.id_asisten=a.id_asisten', 'left');
                $fikri = $this->db->join('hari c', 'c.id_hari=a.hari', 'left');
                $fikri = $this->db->like('a.id_asisten', '131232');
                $fikri = $this->db->where('a.tanggal BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
                $fikri = $this->db->order_by('a.id', 'asc');
                $fikri = $this->db->get()->result();

                $X = 0;
                $tot2 = 0;

                foreach ($fikri as $row) {
                    $X += 1;
                    $t = $row->jam_pulang - $row->jam_mulai; //pengurangan jam pulang - jam masuk. 
                    $h = round($t * 2) / 2; //konversi pengurangan jam agar pas
                    $pdf->Cell(10, 6, $X, 1, 0, 'C');
                    $pdf->Cell(60, 6, $row->nm_asisten, 1, 0, 'C');
                    $pdf->Cell(50, 6, $row->nm_hari . ', ' . date("d-m-Y", strtotime($row->tanggal)), 1, 0, 'C');
                    $pdf->Cell(35, 6, $row->jam_mulai . ' - ' . $row->jam_pulang, 1, 0, 'C');
                    $pdf->Cell(30, 6, $h, 1, 1, 'C');
                    $tot2 += $h;
                }
                $total2 = $tot2 * 8000;
                $pdf->SetFont('Arial', 'B', 9);
                $pdf->Cell(155, 6, 'Total Jam', 1, 0, 'R');
                $pdf->Cell(30, 6, $tot2, 1, 1, 'C');
                $pdf->Cell(155, 6, 'Total Jam x 8000', 1, 0, 'R');
                $pdf->Cell(30, 6, 'Rp.  ' . $total2, 1, 1, 'C');
                //End Fikri

                //Aziz
                $pdf->SetFont('Arial', '', 9);
                $aziz = $this->db->select('*');
                $aziz = $this->db->from('lembur a');
                $aziz = $this->db->join('asisten b', 'b.id_asisten=a.id_asisten', 'left');
                $aziz = $this->db->join('hari c', 'c.id_hari=a.hari', 'left');
                $aziz = $this->db->like('a.id_asisten', '17040044');
                $aziz = $this->db->where('a.tanggal BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
                $aziz = $this->db->order_by('a.id', 'asc');
                $aziz = $this->db->get()->result();

                $X = 0;
                $tot3 = 0;

                foreach ($aziz as $row) {
                    $X += 1;
                    $t = $row->jam_pulang - $row->jam_mulai; //pengurangan jam pulang - jam masuk. 
                    $h = round($t * 2) / 2; //konversi pengurangan jam agar pas
                    $pdf->Cell(10, 6, $X, 1, 0, 'C');
                    $pdf->Cell(60, 6, $row->nm_asisten, 1, 0, 'C');
                    $pdf->Cell(50, 6, $row->nm_hari . ', ' . date("d-m-Y", strtotime($row->tanggal)), 1, 0, 'C');
                    $pdf->Cell(35, 6, $row->jam_mulai . ' - ' . $row->jam_pulang, 1, 0, 'C');
                    $pdf->Cell(30, 6, $h, 1, 1, 'C');
                    $tot3 += $h;
                }
                $total3 = $tot3 * 5000;
                $pdf->SetFont('Arial', 'B', 9);
                $pdf->Cell(155, 6, 'Total Jam', 1, 0, 'R');
                $pdf->Cell(30, 6, $tot3, 1, 1, 'C');
                $pdf->Cell(155, 6, 'Total Jam x 5000', 1, 0, 'R');
                $pdf->Cell(30, 6, 'Rp.  ' . $total3, 1, 1, 'C');
                //Aziz End

                //aldo
                $pdf->SetFont('Arial', '', 9);
                $aldo = $this->db->select('*');
                $aldo = $this->db->from('lembur a');
                $aldo = $this->db->join('asisten b', 'b.id_asisten=a.id_asisten', 'left');
                $aldo = $this->db->join('hari c', 'c.id_hari=a.hari', 'left');
                $aldo = $this->db->like('a.id_asisten', '23232');
                $aldo = $this->db->where('a.tanggal BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
                $aldo = $this->db->order_by('a.id', 'asc');
                $aldo = $this->db->get()->result();

                $X = 0;
                $tot4 = 0;

                foreach ($aldo as $row) {
                    $X += 1;
                    $t = $row->jam_pulang - $row->jam_mulai; //pengurangan jam pulang - jam masuk. 
                    $h = round($t * 2) / 2; //konversi pengurangan jam agar pas
                    $pdf->Cell(10, 6, $X, 1, 0, 'C');
                    $pdf->Cell(60, 6, $row->nm_asisten, 1, 0, 'C');
                    $pdf->Cell(50, 6, $row->nm_hari . ', ' . date("d-m-Y", strtotime($row->tanggal)), 1, 0, 'C');
                    $pdf->Cell(35, 6, $row->jam_mulai . ' - ' . $row->jam_pulang, 1, 0, 'C');
                    $pdf->Cell(30, 6, $h, 1, 1, 'C');
                    $tot4 += $h;
                }
                $total4 = $tot4 * 5000;
                $pdf->SetFont('Arial', 'B', 9);
                $pdf->Cell(155, 6, 'Total Jam', 1, 0, 'R');
                $pdf->Cell(30, 6, $tot4, 1, 1, 'C');
                $pdf->Cell(155, 6, 'Total Jam x 5000', 1, 0, 'R');
                $pdf->Cell(30, 6, 'Rp.  ' . $total4, 1, 1, 'C');
                //aldo End

                //abdil
                $pdf->SetFont('Arial', '', 9);
                $abdil = $this->db->select('*');
                $abdil = $this->db->from('lembur a');
                $abdil = $this->db->join('asisten b', 'b.id_asisten=a.id_asisten', 'left');
                $abdil = $this->db->join('hari c', 'c.id_hari=a.hari', 'left');
                $abdil = $this->db->like('a.id_asisten', '129887');
                $abdil = $this->db->where('a.tanggal BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
                $abdil = $this->db->order_by('a.id', 'asc');
                $abdil = $this->db->get()->result();

                $X = 0;
                $tot5 = 0;

                foreach ($abdil as $row) {
                    $X += 1;
                    $t = $row->jam_pulang - $row->jam_mulai; //pengurangan jam pulang - jam masuk. 
                    $h = round($t * 2) / 2; //konversi pengurangan jam agar pas
                    $pdf->Cell(10, 6, $X, 1, 0, 'C');
                    $pdf->Cell(60, 6, $row->nm_asisten, 1, 0, 'C');
                    $pdf->Cell(50, 6, $row->nm_hari . ', ' . date("d-m-Y", strtotime($row->tanggal)), 1, 0, 'C');
                    $pdf->Cell(35, 6, $row->jam_mulai . ' - ' . $row->jam_pulang, 1, 0, 'C');
                    $pdf->Cell(30, 6, $h, 1, 1, 'C');
                    $tot5 += $h;
                }
                $total5 = $tot5 * 5000;
                $pdf->SetFont('Arial', 'B', 9);
                $pdf->Cell(155, 6, 'Total Jam', 1, 0, 'R');
                $pdf->Cell(30, 6, $tot5, 1, 1, 'C');
                $pdf->Cell(155, 6, 'Total Jam x 5000', 1, 0, 'R');
                $pdf->Cell(30, 6, 'Rp.  ' . $total5, 1, 1, 'C');
                //abdil End

                //total
                $keseluruhan = $total1 + $total2 + $total3 + $total4 + $total5;
                $pdf->Cell(185, 6, '', 1, 1, 'C');
                $pdf->Cell(155, 6, 'Total Keseluruhan', 1, 0, 'R');
                $pdf->Cell(30, 6, 'Rp.   ' . $keseluruhan, 1, 1, 'C');

                $pdf->Ln();
                // setting jenis font yang akan digunakan
                $pdf->SetFont('Arial', '', 11);
                $pdf->Cell(190, 7, 'Tegal, ' . tanggal('d F Y'), 0, 1, 'R');
                $pdf->SetFont('Arial', '', 11);
                $pdf->Cell(190, 7, 'Mengetahui,', 0, 1, 'C');
                $pdf->SetFont('Arial', '', 11);
                $pdf->Cell(95, 6, 'WADIR I', 0, 0, 'C');
                $pdf->SetFont('Arial', '', 11);
                $pdf->Cell(95, 7, 'Ka. UPT. Sistem Informasi', 0, 1, 'C');
                $pdf->Cell(95, 7, 'Politeknik Harapan Bersama Tegal', 0, 0, 'C');
                $pdf->SetFont('Arial', '', 11);
                $pdf->Cell(95, 6, 'Politeknik Harapan Bersama Tegal', 0, 1, 'C');
                $pdf->Ln();
                $pdf->Ln();
                $pdf->Ln();
                $pdf->SetFont('Arial', '' . 'U', 11);
                $pdf->Cell(95, 6, 'Arfan Haqiqi S., M.Kom', 0, 0, 'C');
                $pdf->SetFont('Arial', '' . 'U', 11);
                $pdf->Cell(95, 7, 'Miftakhul Huda, M.Kom', 0, 1, 'C');
                $pdf->SetFont('Arial', '', 11);
                $pdf->Cell(95, 7, 'NIPY. 02.009.054', 0, 0, 'C');
                $pdf->SetFont('Arial', '', 11);
                $pdf->Cell(95, 6, 'NIPY. 04.007.033', 0, 1, 'C');

                $pdf->Output();
            } else {
                $data['_view'] = 'jadwal/rekap';
                if ($this->session->userdata("level") == 'admin') {
                    $this->load->view('layouts/main', $data);
                } else {
                    $this->load->view('layouts/main_user', $data);
                }
            }
        }
    }
}
